language: node_js
node_js: 
  - "8.2.1"

before_install: 
  - export TZ=Europe/Oslo

install:
  - npm install

before_script:
  - npm run checkversions
  - npm run lint
  - npm run postinstall

script:
  - npm run build
  - npm run build-guideline-app

before_deploy:
  - git config --global user.email "eirik@archivedworks.com"
  - git config --global user.name "navikt"

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    keep-history: true
    local-dir: "guideline-app/dist"
  - provider: script
    skip-cleanup: true
    on:
      branch: master
    script:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc && npm run lernapublish