name: Bundle check against npm

on:
  pull_request:
    branches: [main]
    paths:
      - "@navikt/**"

permissions:
  contents: read

jobs:
  analyze:
    name: "Analyzing npm packages"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'Version Packages')
    steps:
      - name: Checkout main-branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          npm_auth_token: ${{ secrets.READER_TOKEN }}

      - name: Analyze npm packages
        run: yarn run:analyze-npm-action

      - name: Analyze trunk and compare against npm packages
        run: yarn run:analyze-branch

      - name: Upload comparison markdown to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: compare-markdown.md
          path: scripts/analyzer
          retention-days: 1

  update-comment:
    name: "Create or update PR comment with results"
    runs-on: ubuntu-latest
    needs: analyze
    if: contains(github.event.pull_request.title, 'Version Packages')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download comparison markdown to GitHub Actions Artifacts
        uses: actions/download-artifact@v7
        with:
          path: scripts/analyzer
          name: compare-markdown.md

      - name: Find Comment
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Bundle Analysis Result

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: scripts/analyzer/compare-markdown.md
          edit-mode: replace
